name: Unity Build

on:  
  push:  
    branches: [ "main" ]  
  pull_request:  
    branches: [ "main" ]  

jobs:  
  build:  
    name: Build Unity Project  
    runs-on: editor-ubuntu-6000.0.45f1-windows-mono-3.1.0  

    steps:  
      - name: Checkout  
        uses: actions/checkout@v4  
        with:  
          lfs: true  # Важно для ассетов  

      - name: Setup Unity  
        uses: game-ci/unity-setup@v2  
        with:  
          unity-version: "2022.3.60f1"  # Укажите свою версию  

      - name: Build  
        uses: game-ci/unity-builder@v3  
        with:  
          targetPlatform: Windows  # Или Windows, Android, iOS и т.д.  
          projectPath: "CraneInspection"  # Путь к папке проекта  